<?php

/**
 * This is the model base class for the table "mip_bank_account".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BankAccount".
 *
 * Columns in table "mip_bank_account" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $bank_id
 * @property string $account_type
 * @property string $number
 *
 */
abstract class BaseBankAccount extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_bank_account';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BankAccount|BankAccounts', $n);
	}

	public static function representingColumn() {
		return 'account_type';
	}

	public function rules() {
		return array(
			array('bank_id, number', 'required'),
			array('bank_id', 'numerical', 'integerOnly'=>true),
			array('account_type', 'length', 'max'=>1),
			array('number', 'length', 'max'=>255),
			array('account_type', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, bank_id, account_type, number', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'bank_id' => Yii::t('app', 'Bank'),
			'account_type' => Yii::t('app', 'Account Type'),
			'number' => Yii::t('app', 'Number'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('bank_id', $this->bank_id);
		$criteria->compare('account_type', $this->account_type, true);
		$criteria->compare('number', $this->number, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}