<?php

/**
 * This is the model base class for the table "mip_accounting_account_kind".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AccountingAccountKind".
 *
 * Columns in table "mip_accounting_account_kind" available as properties of the model,
 * followed by relations of table "mip_accounting_account_kind" available as properties of the model.
 *
 * @property string $key
 * @property string $title
 * @property string $created_at
 * @property string $updated_at
 * @property integer $deprecated
 * @property integer $position
 *
 * @property AccountingAccount[] $accountingAccounts
 */
abstract class BaseAccountingAccountKind extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_accounting_account_kind';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AccountingAccountKind|AccountingAccountKinds', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('key, title, created_at', 'required'),
			array('deprecated, position', 'numerical', 'integerOnly'=>true),
			array('key', 'length', 'max'=>4),
			array('title', 'length', 'max'=>32),
			array('updated_at', 'safe'),
			array('updated_at, deprecated, position', 'default', 'setOnEmpty' => true, 'value' => null),
			array('key, title, created_at, updated_at, deprecated, position', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'accountingAccounts' => array(self::HAS_MANY, 'AccountingAccount', 'kind'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'key' => Yii::t('app', 'Key'),
			'title' => Yii::t('app', 'Title'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'deprecated' => Yii::t('app', 'Deprecated'),
			'position' => Yii::t('app', 'Position'),
			'accountingAccounts' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('key', $this->key, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('deprecated', $this->deprecated);
		$criteria->compare('position', $this->position);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}