<?php

/**
 * This is the model base class for the table "mip_accounting_move_status".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AccountingMoveStatus".
 *
 * Columns in table "mip_accounting_move_status" available as properties of the model,
 * followed by relations of table "mip_accounting_move_status" available as properties of the model.
 *
 * @property string $key
 * @property string $label
 *
 * @property AccountingMove[] $accountingMoves
 */
abstract class BaseAccountingMoveStatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_accounting_move_status';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AccountingMoveStatus|AccountingMoveStatuses', $n);
	}

	public static function representingColumn() {
		return 'label';
	}

	public function rules() {
		return array(
			array('key, label', 'required'),
			array('key', 'length', 'max'=>4),
			array('label', 'length', 'max'=>64),
			array('key, label', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'accountingMoves' => array(self::HAS_MANY, 'AccountingMove', 'status'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'key' => Yii::t('app', 'Key'),
			'label' => Yii::t('app', 'Label'),
			'accountingMoves' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('key', $this->key, true);
		$criteria->compare('label', $this->label, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}