<?php

/**
 * This is the model base class for the table "mip_account_period_status".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AccountPeriodStatus".
 *
 * Columns in table "mip_account_period_status" available as properties of the model,
 * followed by relations of table "mip_account_period_status" available as properties of the model.
 *
 * @property string $key
 * @property string $label
 * @property integer $at_year
 * @property integer $at_period
 * @property string $created_at
 * @property string $updated_at
 *
 * @property AccountingPeriod[] $accountingPeriods
 * @property FiscalYear[] $fiscalYears
 */
abstract class BaseAccountingPeriodStatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_accounting_period_status';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AccountPeriodStatus|AccountPeriodStatuses', $n);
	}

	public static function representingColumn() {
		return 'label';
	}

	public function rules() {
		return array(
			array('key, label, at_year, at_period, created_at', 'required'),
			array('at_year, at_period', 'numerical', 'integerOnly'=>true),
			array('key', 'length', 'max'=>4),
			array('label', 'length', 'max'=>64),
			array('updated_at', 'safe'),
			array('updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('key, label, at_year, at_period, created_at, updated_at', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'accountingPeriods' => array(self::HAS_MANY, 'AccountingPeriod', 'status'),
			'fiscalYears' => array(self::HAS_MANY, 'FiscalYear', 'status'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'key' => Yii::t('app', 'Key'),
			'label' => Yii::t('app', 'Label'),
			'at_year' => Yii::t('app', 'At Year'),
			'at_period' => Yii::t('app', 'At Period'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'accountingPeriods' => null,
			'fiscalYears' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('key', $this->key, true);
		$criteria->compare('label', $this->label, true);
		$criteria->compare('at_year', $this->at_year);
		$criteria->compare('at_period', $this->at_period);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}