<?php

/**
 * This is the model base class for the table "mip_accounting_move_ref_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AccountingMoveRefType".
 *
 * Columns in table "mip_accounting_move_ref_type" available as properties of the model,
 * followed by relations of table "mip_accounting_move_ref_type" available as properties of the model.
 *
 * @property string $key
 * @property string $title
 * @property string $associated_name
 *
 * @property MipAccountingMove[] $mipAccountingMoves
 */
abstract class BaseAccountingMoveRefType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_accounting_move_ref_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AccountingMoveRefType|AccountingMoveRefTypes', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

	public function rules() {
		return array(
			array('key, title, associated_name', 'required'),
			array('key', 'length', 'max'=>8),
			array('title, associated_name', 'length', 'max'=>64),
			array('key, title, associated_name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'mipAccountingMoves' => array(self::HAS_MANY, 'MipAccountingMove', 'ref_type'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'key' => Yii::t('app', 'Key'),
			'title' => Yii::t('app', 'Title'),
			'associated_name' => Yii::t('app', 'Associated Name'),
			'mipAccountingMoves' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('key', $this->key, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('associated_name', $this->associated_name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}