<?php

/**
 * This is the model base class for the table "mip_person_email".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PersonEmail".
 *
 * Columns in table "mip_person_email" available as properties of the model,
 * followed by relations of table "mip_person_email" available as properties of the model.
 *
 * @property integer $id
 * @property integer $person_id
 * @property string $email
 * @property integer $is_main
 *
 * @property Person $person
 */
abstract class BasePersonEmail extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_person_email';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PersonEmail|PersonEmails', $n);
	}

	public static function representingColumn() {
		return 'email';
	}

	public function rules() {
		return array(
			array('person_id, email', 'required'),
			array('person_id, is_main', 'numerical', 'integerOnly'=>true),
			array('is_main', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, person_id, email, is_main', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'person' => array(self::BELONGS_TO, 'Person', 'person_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'person_id' => null,
			'email' => Yii::t('app', 'Email'),
			'is_main' => Yii::t('app', 'Is Main'),
			'person' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('person_id', $this->person_id);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('is_main', $this->is_main);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}