<?php

/**
 * This is the model base class for the table "mip_bank_account_entry".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BankAccountEntry".
 *
 * Columns in table "mip_bank_account_entry" available as properties of the model,
 * followed by relations of table "mip_bank_account_entry" available as properties of the model.
 *
 * @property integer $id
 * @property string $begin_date
 * @property string $end_date
 * @property string $number
 * @property string $summary
 * @property string $value
 * @property string $type
 * @property integer $position
 * @property string $balance
 * @property integer $bank_account_summary_id
 *
 * @property BankAccountSummary $bankAccountSummary
 */
abstract class BaseBankAccountEntry extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_bank_account_entry';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'BankAccountEntry|BankAccountEntries', $n);
	}

	public static function representingColumn() {
		return 'begin_date';
	}

	public function rules() {
		return array(
			array('begin_date, end_date, number, summary, value, type, position, balance, bank_account_summary_id', 'required'),
			array('position, bank_account_summary_id', 'numerical', 'integerOnly'=>true),
			array('number', 'length', 'max'=>16),
			array('summary', 'length', 'max'=>255),
			array('value, balance', 'length', 'max'=>10),
			array('type', 'length', 'max'=>1),
			array('id, begin_date, end_date, number, summary, value, type, position, balance, bank_account_summary_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'bankAccountSummary' => array(self::BELONGS_TO, 'BankAccountSummary', 'bank_account_summary_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'begin_date' => Yii::t('app', 'Begin Date'),
			'end_date' => Yii::t('app', 'End Date'),
			'number' => Yii::t('app', 'Number'),
			'summary' => Yii::t('app', 'Summary'),
			'value' => Yii::t('app', 'Value'),
			'type' => Yii::t('app', 'Type'),
			'position' => Yii::t('app', 'Position'),
			'balance' => Yii::t('app', 'Balance'),
			'bank_account_summary_id' => null,
			'bankAccountSummary' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('begin_date', $this->begin_date, true);
		$criteria->compare('end_date', $this->end_date, true);
		$criteria->compare('number', $this->number, true);
		$criteria->compare('summary', $this->summary, true);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('position', $this->position);
		$criteria->compare('balance', $this->balance, true);
		$criteria->compare('bank_account_summary_id', $this->bank_account_summary_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}