<?php

/**
 * This is the model base class for the table "mip_owner".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Owner".
 *
 * Columns in table "mip_owner" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $location_id
 * @property integer $person_id
 * @property string $begin_date
 * @property string $end_date
 *
 */
abstract class BaseOwner extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_owner';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Owner|Owners', $n);
	}

	public static function representingColumn() {
		return 'begin_date';
	}

	public function rules() {
		return array(
			array('location_id, person_id, begin_date', 'required'),
			array('location_id, person_id', 'numerical', 'integerOnly'=>true),
			array('end_date', 'safe'),
			array('end_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, location_id, person_id, begin_date, end_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'location_id' => Yii::t('app', 'Location'),
			'person_id' => Yii::t('app', 'Person'),
			'begin_date' => Yii::t('app', 'Begin Date'),
			'end_date' => Yii::t('app', 'End Date'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('location_id', $this->location_id);
		$criteria->compare('person_id', $this->person_id);
		$criteria->compare('begin_date', $this->begin_date, true);
		$criteria->compare('end_date', $this->end_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}