<?php

/**
 * This is the model base class for the table "mip_accounting_period".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AccountingPeriod".
 *
 * Columns in table "mip_accounting_period" available as properties of the model,
 * followed by relations of table "mip_accounting_period" available as properties of the model.
 *
 * @property integer $id
 * @property string $label
 * @property string $from
 * @property string $to
 * @property integer $fiscal_year_id
 * @property string $created_at
 * @property string $updated_at
 * @property string $status
 *
 * @property AccountingMoveLine[] $accountingMoveLines
 * @property FiscalYear $fiscalYear
 * @property AccountingPeriodStatus $status0
 */
abstract class BaseAccountingPeriod extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_accounting_period';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AccountingPeriod|AccountingPeriods', $n);
	}

	public static function representingColumn() {
		return 'label';
	}

	public function rules() {
		return array(
			array('label, from, to, fiscal_year_id, created_at, status', 'required'),
			array('fiscal_year_id', 'numerical', 'integerOnly'=>true),
			array('label', 'length', 'max'=>64),
			array('status', 'length', 'max'=>4),
			array('updated_at', 'safe'),
			array('updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, label, from, to, fiscal_year_id, created_at, updated_at, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'accountingMoveLines' => array(self::HAS_MANY, 'AccountingMoveLine', 'accounting_period_id'),
			'fiscalYear' => array(self::BELONGS_TO, 'FiscalYear', 'fiscal_year_id'),
			'status0' => array(self::BELONGS_TO, 'AccountPeriodStatus', 'status'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'label' => Yii::t('app', 'Label'),
			'from' => Yii::t('app', 'From'),
			'to' => Yii::t('app', 'To'),
			'fiscal_year_id' => null,
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'status' => null,
			'accountingMoveLines' => null,
			'fiscalYear' => null,
			'status0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('label', $this->label, true);
		$criteria->compare('from', $this->from, true);
		$criteria->compare('to', $this->to, true);
		$criteria->compare('fiscal_year_id', $this->fiscal_year_id);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}