<?php

/**
 * This is the model base class for the table "mip_person_address".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PersonAddress".
 *
 * Columns in table "mip_person_address" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $person_id
 * @property string $address_1
 * @property string $address_2
 * @property integer $state_id
 * @property string $city
 * @property integer $is_main
 *
 */
abstract class BasePersonAddress extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_person_address';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PersonAddress|PersonAddresses', $n);
	}

	public static function representingColumn() {
		return 'address_1';
	}

	public function rules() {
		return array(
			array('person_id, address_1, state_id, city', 'required'),
			array('person_id, state_id, is_main', 'numerical', 'integerOnly'=>true),
			array('address_1, address_2, city', 'length', 'max'=>255),
			array('address_2, is_main', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, person_id, address_1, address_2, state_id, city, is_main', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'person_id' => Yii::t('app', 'Person'),
			'address_1' => Yii::t('app', 'Address 1'),
			'address_2' => Yii::t('app', 'Address 2'),
			'state_id' => Yii::t('app', 'State'),
			'city' => Yii::t('app', 'City'),
			'is_main' => Yii::t('app', 'Is Main'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('person_id', $this->person_id);
		$criteria->compare('address_1', $this->address_1, true);
		$criteria->compare('address_2', $this->address_2, true);
		$criteria->compare('state_id', $this->state_id);
		$criteria->compare('city', $this->city, true);
		$criteria->compare('is_main', $this->is_main);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}