<?php

/**
 * This is the model base class for the table "mip_bank".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Bank".
 *
 * Columns in table "mip_bank" available as properties of the model,
 * followed by relations of table "mip_bank" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $akey
 *
 * @property BankAccount[] $bankAccounts
 * @property PayNotCashInfo[] $payNotCashInfos
 */
abstract class BaseBank extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_bank';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Bank|Banks', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>255),
			array('akey', 'length', 'max'=>3),
			array('akey', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, akey', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'bankAccounts' => array(self::HAS_MANY, 'BankAccount', 'bank_id'),
			'payNotCashInfos' => array(self::HAS_MANY, 'PayNotCashInfo', 'source_bank_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'akey' => Yii::t('app', 'Akey'),
			'bankAccounts' => null,
			'payNotCashInfos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('akey', $this->akey, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}