<?php

/**
 * This is the model base class for the table "mip_pay".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Pay".
 *
 * Columns in table "mip_pay" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $pay_date
 * @property string $value_cash
 * @property integer $person_id
 *
 */
abstract class BasePay extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_pay';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Pay|Pays', $n);
	}

	public static function representingColumn() {
		return 'pay_date';
	}

	public function rules() {
		return array(
			array('pay_date, value_cash, person_id', 'required'),
			array('person_id', 'numerical', 'integerOnly'=>true),
			array('value_cash', 'length', 'max'=>10),
			array('id, pay_date, value_cash, person_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'pay_date' => Yii::t('app', 'Pay Date'),
			'value_cash' => Yii::t('app', 'Value Cash'),
			'person_id' => Yii::t('app', 'Mip Person'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('pay_date', $this->pay_date, true);
		$criteria->compare('value_cash', $this->value_cash, true);
		$criteria->compare('person_id', $this->person_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}