<?php

/**
 * This is the model base class for the table "mip_log".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Log".
 *
 * Columns in table "mip_log" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $user
 * @property string $table
 * @property string $description
 * @property string $log_date
 *
 */
abstract class BaseLog extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_log';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Log|Logs', $n);
	}

	public static function representingColumn() {
		return 'user';
	}

	public function rules() {
		return array(
			array('id', 'required'),
			array('id', 'numerical', 'integerOnly'=>true),
			array('user', 'length', 'max'=>45),
			array('table', 'length', 'max'=>90),
			array('description, log_date', 'safe'),
			array('user, table, description, log_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, user, table, description, log_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'user' => Yii::t('app', 'User'),
			'table' => Yii::t('app', 'Table'),
			'description' => Yii::t('app', 'Description'),
			'log_date' => Yii::t('app', 'Log Date'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('user', $this->user, true);
		$criteria->compare('table', $this->table, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('log_date', $this->log_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}