<?php

/**
 * This is the model base class for the table "mip_accounting_move_line".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AccountingMoveLine".
 *
 * Columns in table "mip_accounting_move_line" available as properties of the model,
 * followed by relations of table "mip_accounting_move_line" available as properties of the model.
 *
 * @property integer $id
 * @property string $label
 * @property integer $accounting_move_id
 * @property integer $accounting_account_id
 * @property integer $accounting_period_id
 * @property string $debt
 * @property string $credt
 * @property string $date_at
 * @property string $created_at
 * @property string $updated_at
 * @property integer $reconciled
 *
 * @property AccountingAccount $accountingAccount
 * @property AccountingMove $accountingMove
 * @property AccountingPeriod $accountingPeriod
 */
abstract class BaseAccountingMoveLine extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_accounting_move_line';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AccountingMoveLine|AccountingMoveLines', $n);
	}

	public static function representingColumn() {
		return 'debt';
	}

	public function rules() {
		return array(
			array('accounting_move_id, accounting_account_id, accounting_period_id, debt, credt, date_at, created_at, reconciled', 'required'),
			array('accounting_move_id, accounting_account_id, accounting_period_id, reconciled', 'numerical', 'integerOnly'=>true),
			array('label', 'length', 'max'=>128),
			array('debt, credt', 'length', 'max'=>10),
			array('updated_at', 'safe'),
			array('label, updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, label, accounting_move_id, accounting_account_id, accounting_period_id, debt, credt, date_at, created_at, updated_at, reconciled', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'accountingAccount' => array(self::BELONGS_TO, 'AccountingAccount', 'accounting_account_id'),
			'accountingMove' => array(self::BELONGS_TO, 'AccountingMove', 'accounting_move_id'),
			'accountingPeriod' => array(self::BELONGS_TO, 'AccountingPeriod', 'accounting_period_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'label' => Yii::t('app', 'Label'),
			'accounting_move_id' => null,
			'accounting_account_id' => null,
			'accounting_period_id' => null,
			'debt' => Yii::t('app', 'Debt'),
			'credt' => Yii::t('app', 'Credt'),
			'date_at' => Yii::t('app', 'Date At'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'reconciled' => Yii::t('app', 'Reconciled'),
			'accountingAccount' => null,
			'accountingMove' => null,
			'accountingPeriod' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('label', $this->label, true);
		$criteria->compare('accounting_move_id', $this->accounting_move_id);
		$criteria->compare('accounting_account_id', $this->accounting_account_id);
		$criteria->compare('accounting_period_id', $this->accounting_period_id);
		$criteria->compare('debt', $this->debt, true);
		$criteria->compare('credt', $this->credt, true);
		$criteria->compare('date_at', $this->date_at, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('reconciled', $this->reconciled);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}