<?php

/**
 * This is the model base class for the table "mip_fee_pay".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FeePay".
 *
 * Columns in table "mip_fee_pay" available as properties of the model,
 * followed by relations of table "mip_fee_pay" available as properties of the model.
 *
 * @property integer $id
 * @property integer $pay_id
 * @property integer $fee_id
 * @property integer $location_id
 *
 * @property Fee $fee
 * @property Location $location
 * @property Pay $pay
 */
abstract class BaseFeePay extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_fee_pay';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FeePay|FeePays', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('pay_id, fee_id, location_id', 'required'),
			array('pay_id, fee_id, location_id', 'numerical', 'integerOnly'=>true),
			array('id, pay_id, fee_id, location_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'fee' => array(self::BELONGS_TO, 'Fee', 'fee_id'),
			'location' => array(self::BELONGS_TO, 'Location', 'location_id'),
			'pay' => array(self::BELONGS_TO, 'Pay', 'pay_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'pay_id' => null,
			'fee_id' => null,
			'location_id' => null,
			'fee' => null,
			'location' => null,
			'pay' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('pay_id', $this->pay_id);
		$criteria->compare('fee_id', $this->fee_id);
		$criteria->compare('location_id', $this->location_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}