<?php

/**
 * This is the model base class for the table "view_location_fee_pay".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ViewLocationFeePay".
 *
 * Columns in table "view_location_fee_pay" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $feed_id
 * @property string $name
 * @property string $summary
 * @property string $begin_date
 * @property string $end_date
 * @property string $value
 * @property integer $location_id
 * @property string $code
 * @property string $status
 * @property integer $pay_id
 * @property integer $fee_pay_id
 * @property integer $fee_payed
 *
 */
abstract class BaseViewLocationFeePay extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'view_location_fee_pay';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ViewLocationFeePay|ViewLocationFeePays', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, summary, begin_date, end_date, value, code', 'required'),
			array('feed_id, location_id, pay_id, fee_pay_id, fee_payed', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>60),
			array('summary', 'length', 'max'=>255),
			array('value, code', 'length', 'max'=>10),
			array('status', 'length', 'max'=>1),
			array('feed_id, location_id, status, pay_id, fee_pay_id, fee_payed', 'default', 'setOnEmpty' => true, 'value' => null),
			array('feed_id, name, summary, begin_date, end_date, value, location_id, code, status, pay_id, fee_pay_id, fee_payed', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'feed_id' => Yii::t('app', 'Feed'),
			'name' => Yii::t('app', 'Name'),
			'summary' => Yii::t('app', 'Summary'),
			'begin_date' => Yii::t('app', 'Begin Date'),
			'end_date' => Yii::t('app', 'End Date'),
			'value' => Yii::t('app', 'Value'),
			'location_id' => Yii::t('app', 'Location'),
			'code' => Yii::t('app', 'Code'),
			'status' => Yii::t('app', 'Status'),
			'pay_id' => Yii::t('app', 'Pay'),
			'fee_pay_id' => Yii::t('app', 'Fee Pay'),
			'fee_payed' => Yii::t('app', 'Fee Payed'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('feed_id', $this->feed_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('summary', $this->summary, true);
		$criteria->compare('begin_date', $this->begin_date, true);
		$criteria->compare('end_date', $this->end_date, true);
		$criteria->compare('value', $this->value, true);
		$criteria->compare('location_id', $this->location_id);
		$criteria->compare('code', $this->code, true);
		$criteria->compare('status', $this->status, true);
		$criteria->compare('pay_id', $this->pay_id);
		$criteria->compare('fee_pay_id', $this->fee_pay_id);
		$criteria->compare('fee_payed', $this->fee_payed);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}