<?php

/**
 * This is the model base class for the table "mip_fiscal_year".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FiscalYear".
 *
 * Columns in table "mip_fiscal_year" available as properties of the model,
 * followed by relations of table "mip_fiscal_year" available as properties of the model.
 *
 * @property integer $id
 * @property string $label
 * @property string $from
 * @property string $to
 * @property string $created_at
 * @property string $updated_at
 * @property integer $is_closed
 * @property string $status
 *
 * @property AccountingPeriod[] $accountingPeriods
 * @property AccountingPeriodStatus $status0
 */
abstract class BaseFiscalYear extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_fiscal_year';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FiscalYear|FiscalYears', $n);
	}

	public static function representingColumn() {
		return 'label';
	}

	public function rules() {
		return array(
			array('label, from, to, created_at, is_closed, status', 'required'),
			array('is_closed', 'numerical', 'integerOnly'=>true),
			array('label', 'length', 'max'=>64),
			array('status', 'length', 'max'=>4),
			array('updated_at', 'safe'),
			array('updated_at', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, label, from, to, created_at, updated_at, is_closed, status', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'accountingPeriods' => array(self::HAS_MANY, 'AccountingPeriod', 'fiscal_year_id'),
			'status0' => array(self::BELONGS_TO, 'AccountingPeriodStatus', 'status'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'label' => Yii::t('app', 'Label'),
			'from' => Yii::t('app', 'From'),
			'to' => Yii::t('app', 'To'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'is_closed' => Yii::t('app', 'Is Closed'),
			'status' => null,
			'accountingPeriods' => null,
			'status0' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('label', $this->label, true);
		$criteria->compare('from', $this->from, true);
		$criteria->compare('to', $this->to, true);
		$criteria->compare('created_at', $this->created_at, true);
		$criteria->compare('updated_at', $this->updated_at, true);
		$criteria->compare('is_closed', $this->is_closed);
		$criteria->compare('status', $this->status);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}