<?php

/**
 * This is the model base class for the table "mip_resident_association".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ResidentAssociation".
 *
 * Columns in table "mip_resident_association" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $person_id
 * @property integer $mip_association_position_id
 *
 */
abstract class BaseResidentAssociation extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_resident_association';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ResidentAssociation|ResidentAssociations', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('person_id, association_position_id', 'required'),
			array('person_id, association_position_id', 'numerical', 'integerOnly'=>true),
			array('id, person_id, association_position_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'person_id' => Yii::t('app', 'Person'),
			'association_position_id' => Yii::t('app', 'Association Position'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('person_id', $this->person_id);
		$criteria->compare('association_position_id', $this->association_position_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}