<?php

/**
 * This is the model base class for the table "mip_accounting_account_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AccountingAccountType".
 *
 * Columns in table "mip_accounting_account_type" available as properties of the model,
 * followed by relations of table "mip_accounting_account_type" available as properties of the model.
 *
 * @property string $key
 * @property string $label
 * @property integer $is_debt
 *
 * @property AccountingAccount[] $accountingAccounts
 */
abstract class BaseAccountingAccountType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_accounting_account_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'AccountingAccountType|AccountingAccountTypes', $n);
	}

	public static function representingColumn() {
		return 'label';
	}

	public function rules() {
		return array(
			array('key, label, is_debt', 'required'),
			array('is_debt', 'numerical', 'integerOnly'=>true),
			array('key', 'length', 'max'=>4),
			array('label', 'length', 'max'=>64),
			array('key, label, is_debt', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'accountingAccounts' => array(self::HAS_MANY, 'AccountingAccount', 'type'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'key' => Yii::t('app', 'Key'),
			'label' => Yii::t('app', 'Label'),
			'is_debt' => Yii::t('app', 'Is Debt'),
			'accountingAccounts' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('key', $this->key, true);
		$criteria->compare('label', $this->label, true);
		$criteria->compare('is_debt', $this->is_debt);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}