<?php

/**
 * This is the model base class for the table "mip_location_geometry".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LocationGeometry".
 *
 * Columns in table "mip_location_geometry" available as properties of the model,
 * followed by relations of table "mip_location_geometry" available as properties of the model.
 *
 * @property integer $id
 * @property string $the_geom
 * @property integer $location_id
 *
 * @property Location $location
 */
abstract class BaseLocationGeometry extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'mip_location_geometry';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LocationGeometry|LocationGeometries', $n);
	}

	public static function representingColumn() {
		return 'the_geom';
	}

	public function rules() {
		return array(
			array('the_geom, location_id', 'required'),
			array('location_id', 'numerical', 'integerOnly'=>true),
			array('the_geom', 'length', 'max'=>255),
			array('id, the_geom, location_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'location' => array(self::BELONGS_TO, 'Location', 'location_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'the_geom' => Yii::t('app', 'The Geom'),
			'location_id' => null,
			'location' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('the_geom', $this->the_geom, true);
		$criteria->compare('location_id', $this->location_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}