<?php

Yii::import('application.models._base.BaseAccountingJournal');

/**
 * This is the model base class for the table "mip_accounting_journal".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AccountingJournal".
 *
 * Columns in table "mip_accounting_journal" available as properties of the model,
 * followed by relations of table "mip_accounting_journal" available as properties of the model.
 *
 * @property integer $id
 * @property string $code
 * @property string $title
 * @property string $note
 * @property string $journal_type
 * @property integer $deprecated
 * @property string $created_at
 * @property string $updated_at
 *
 * @property AccountingJournalType $journalType
 * @property AccountingMove $accountingMove
 */
class AccountingJournal extends BaseAccountingJournal
{
    
    
    /**
     * 
     * @return [string]
     */
    public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'code' => Yii::t('app', 'Code'),
			'title' => Yii::t('app', 'Title'),
			'note' => Yii::t('app', 'Note'),
			'credt_account_id' => null,
			'debt_account_id' => null,
			'journal_type' => null,
			'deprecated' => Yii::t('app', 'Deprecated'),
			'created_at' => Yii::t('app', 'Created At'),
			'updated_at' => Yii::t('app', 'Updated At'),
			'credtAccount' => null,
			'debtAccount' => null,
			'journalType' => null,
			'accountingMoves' => null,
		);
	}
    
    /**
     * 
     * @param type $className
     * @return type
     */
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

}